sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django~=1.8.0"
  - DJANGO="Django~=1.9.0"
  - DJANGO="Django~=1.10.0"
  - DJANGO="Django~=1.11.0"
  - DJANGO="Django~=2.0.0"

matrix:
  exclude:
    - env: DJANGO="Django~=1.9.0"
      python: "3.3"
    - env: DJANGO="Django~=1.9.0"
      python: "pypy3"
    - env: DJANGO="Django~=1.10.0"
      python: "3.3"
    - env: DJANGO="Django~=1.10.0"
      python: "pypy3"
    - env: DJANGO="Django~=1.11.0"
      python: "3.3"
    - env: DJANGO="Django~=1.11.0"
      python: "pypy3"
    - env: DJANGO="Django~=2.0.0"
      python: "2.7"
    - env: DJANGO="Django~=2.0.0"
      python: "3.3"

install:
  - pip install -q $DJANGO coverage
script:
  - coverage run --source mail_builder runtests.py
after_script:
  - coverage report
