sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django<1.8"
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"

matrix:
  exclude:
    - env: DJANGO="Django<1.10"
      python: "3.3"

install:
  - pip install -q $DJANGO
script:
  - python runtests.py
